### ISSUE TITLE
Obsolete version on PyPI

### ISSUE THREAD

**Issue by metamatik** [damianbraun/nominatim#3]
Hi Damian,

I am using your library on my current work project — thanks for sharing! :+1: 

I just investigated a bug in my code, which I solved by adding a call to `quote_plus`, but then I saw in your repo that there was already one such call. Then I understood: the PyPI version is obsolete. :smile: 

Do you have plans to update it?
Or should I fork your repo and package a version to use on our own private PyPI server?

Thanks in advance! :smiley:

**Comment by damianbraun** [comment]
Hey,

I just updated it. :)

**Comment by metamatik** [comment]
Thanks! Much appreciated :-)
